#!/bin/sh
set -o errexit

remote="$1"
if [ "$remote" != "origin" ]; then
    exit 0
fi

type ghp-import >/dev/null
last_commit_message=$(git log -1 --pretty=%s)
cd "$(dirname "$0")/../.."
make github LAST_COMMIT_MESSAGE="$last_commit_message"
